param(
    [string]$AshitaRoot = 'C:\Games\CatsEyeXI\catseyexi-client\Ashita',
    [switch]$EnableTemporaryItemsBar
)

$ErrorActionPreference = 'Stop'

$sourceRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$source = Join-Path $sourceRoot 'ashitabars'
$addonsRoot = Join-Path $AshitaRoot 'addons'
$target = Join-Path $addonsRoot 'ashitabars'
$backupRoot = Join-Path $sourceRoot '.local-backups'
$stamp = Get-Date -Format 'yyyyMMdd-HHmmss'

function Assert-UnderRoot {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Root,
        [Parameter(Mandatory)][string]$Label
    )

    $resolvedRoot = [IO.Path]::GetFullPath($Root)
    $resolvedPath = [IO.Path]::GetFullPath($Path)
    if (-not $resolvedPath.StartsWith($resolvedRoot, [StringComparison]::OrdinalIgnoreCase)) {
        throw "$Label path is outside expected root. Path: $resolvedPath Root: $resolvedRoot"
    }

    return $resolvedPath
}

function Get-LuaSettingLiteral {
    param(
        [Parameter(Mandatory)][string]$Content,
        [Parameter(Mandatory)][string]$Name
    )

    $match = [regex]::Match($Content, "(?m)^\s*$([regex]::Escape($Name))\s*=\s*([^,\r\n]+),?")
    if ($match.Success) {
        return $match.Groups[1].Value.Trim()
    }

    return $null
}

function Save-VisualSettingsMigration {
    param(
        [Parameter(Mandatory)][string]$InstalledAddonPath,
        [Parameter(Mandatory)][string]$AshitaRoot
    )

    $installedConfig = Join-Path $InstalledAddonPath 'ashitabars_config.lua'
    if (-not (Test-Path -LiteralPath $installedConfig)) {
        return
    }

    $configRoot = Join-Path $AshitaRoot 'config\addons\ashitabars'
    $visualSettings = Join-Path $configRoot 'visual_settings.lua'
    if (Test-Path -LiteralPath $visualSettings) {
        return
    }

    $content = Get-Content -LiteralPath $installedConfig -Raw
    $keys = @(
        'display_mode',
        'slot_size',
        'button_gap',
        'slot_glow_size',
        'slot_glow_opacity',
        'label_vertical_position',
        'show_weaponskill_pulse',
        'show_weaponskill_flames',
        'show_bar_frame',
        'window_x',
        'window_y'
    )

    $settings = foreach ($key in $keys) {
        $literal = Get-LuaSettingLiteral -Content $content -Name $key
        if ($null -ne $literal -and $literal -ne '') {
            "        $key = $literal,"
        }
    }

    if (-not $settings -or $settings.Count -eq 0) {
        return
    }

    New-Item -ItemType Directory -Force -Path $configRoot | Out-Null
    $lines = @(
        '-- Generated by AshitaBars install migration. Runtime visual settings are stored here.',
        '-- This file lives outside the addon folder so installs do not reset placement or sizing.',
        'return {',
        '    settings = {'
    ) + $settings + @(
        '    },',
        '}'
    )

    Set-Content -LiteralPath $visualSettings -Value $lines -Encoding ASCII
    Write-Host "Migrated visual settings to: $visualSettings"
}

function Enable-TemporaryItemsBarSettings {
    param(
        [Parameter(Mandatory)][string]$AshitaRoot
    )

    $visualSettings = Join-Path $AshitaRoot 'config\addons\ashitabars\visual_settings.lua'
    if (-not (Test-Path -LiteralPath $visualSettings)) {
        return
    }

    $content = Get-Content -LiteralPath $visualSettings -Raw
    $blockPattern = '(?ms)(^        extra_bar_4\s*=\s*\{)(.*?)(^        \},)'
    $match = [regex]::Match($content, $blockPattern)
    if (-not $match.Success) {
        throw "Could not find extra_bar_4 in: $visualSettings"
    }

    $body = $match.Groups[2].Value
    $values = [ordered]@{
        visible = 'true'
        profile_scope = "'global'"
        button_count = '3'
        buttons_per_row = '3'
        slot_size = '48'
        button_gap = '4'
    }
    foreach ($entry in $values.GetEnumerator()) {
        $settingPattern = "(?m)^(\s*$([regex]::Escape($entry.Key))\s*=\s*)[^,\r\n]+(,.*)$"
        if (-not [regex]::IsMatch($body, $settingPattern)) {
            throw "Could not find $($entry.Key) in extra_bar_4: $visualSettings"
        }
        $body = [regex]::Replace($body, $settingPattern, "`${1}$($entry.Value)`${2}", 1)
    }

    $replacement = $match.Groups[1].Value + $body + $match.Groups[3].Value
    $updated = $content.Substring(0, $match.Index) + $replacement + $content.Substring($match.Index + $match.Length)
    [IO.File]::WriteAllText($visualSettings, $updated, [Text.UTF8Encoding]::new($false))
    Write-Host "Enabled compact Temporary Items bar in: $visualSettings"
}

if (-not (Test-Path -LiteralPath $AshitaRoot)) {
    throw "Ashita root does not exist: $AshitaRoot"
}

if (-not (Test-Path -LiteralPath $source)) {
    throw "Addon source does not exist: $source"
}

$addonsRoot = Assert-UnderRoot -Path $addonsRoot -Root $AshitaRoot -Label 'Ashita addons root'
$target = Assert-UnderRoot -Path $target -Root $addonsRoot -Label 'AshitaBars install target'

New-Item -ItemType Directory -Force -Path $addonsRoot | Out-Null
New-Item -ItemType Directory -Force -Path $backupRoot | Out-Null

if (Test-Path -LiteralPath $target) {
    Save-VisualSettingsMigration -InstalledAddonPath $target -AshitaRoot $AshitaRoot

    $backup = Join-Path $backupRoot "ashitabars-$stamp"
    Move-Item -LiteralPath $target -Destination $backup
    Write-Host "Backed up existing addon to: $backup"
}

Copy-Item -LiteralPath $source -Destination $target -Recurse -Force
Write-Host "Installed AshitaBars addon: $target"

if ($EnableTemporaryItemsBar) {
    Enable-TemporaryItemsBarSettings -AshitaRoot $AshitaRoot
}

